// playground/webpack-next/src/components/Notes.tsx
export default function Notes() {
  return (
    <div>
      <p>
        press hotkey ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> +{' '}
        <kbd>O</kbd>, then click the HTML element you wish to inspect.
      </p>
      <p>
        press hotkey ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> +{' '}
        <kbd>O</kbd>, then press hotkey ⌨️ <kbd>command ⌘</kbd> + 🖱 click, show
        component tree.
      </p>
      <p>
        press hotkey ⌨️ <kbd>esc</kbd> or 🖱 right-click to exit inspect.
      </p>
    </div>
  );
}

// playground/rollup-vue2/src/components/Notes.vue
<template>
  <div>
    <p>
      press hotkey ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> + <kbd>O</kbd>,
      then click the HTML element you wish to inspect.
    </p>
    <p>
      press hotkey ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> + <kbd>O</kbd>,
      then press hotkey ⌨️ <kbd>command ⌘</kbd> + 🖱 click, show component tree.
    </p>
    <p>press hotkey ⌨️ <kbd>esc</kbd> or 🖱 right-click to exit inspect.</p>
  </div>
</template>
