// playground/vite-qwik/src/app.tsx
import { component$ } from '@builder.io/qwik';
import Notes from './Notes';
import './app.css';

export const App = component$(() => {
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://qwik.builder.io" target="_blank">
          <img src="/qwik.svg" class="logo qwik" alt="Qwik logo" />
        </a>
      </div>
      <h1>Vite + Qwik</h1>
      <div class="card">
        <Notes />
      </div>
      <p class="read-the-docs">
        <a target="_black" href="https://github.com/zjxxxxxxxxx/open-editor">
          Github
        </a>
      </p>
    </>
  );
});

// playground/rollup-react/src/App.tsx
import rollupLogo from '../public/rollup.svg';
import reactLogo from '../public/react.svg';
import Notes from './Notes';
import './App.css';

export default function App() {
  return (
    <>
      <div>
        <a href="https://rollupjs.org" target="_blank">
          <img src={rollupLogo} className="logo" alt="Rollup logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Rollup + React</h1>
      <div className="card">
        <Notes />
      </div>
      <p className="read-the-docs">
        <a target="_black" href="https://github.com/zjxxxxxxxxx/open-editor">
          Click to Github
        </a>
      </p>
    </>
  );
}
