// playground/webpack-next/src/Notes.tsx
import Tree from './tree';

export default function Notes() {
  return (
    <>
      <p>
        press hotkey ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> +{' '}
        <kbd>O</kbd>, then click the HTML element you wish to inspect.
      </p>
      <p>
        press hotkey ⌨️ <kbd>command ⌘</kbd> + 🖱 click, show component tree.
      </p>
      <Tree />
      <p>
        press hotkey ⌨️ <kbd>esc</kbd> or 🖱 right-click to exit inspect.
      </p>
    </>
  );
}

// playground/vite-qwik/src/Notes.tsx
import { component$ } from '@builder.io/qwik';
import Tree from './tree';

const Notes = component$(() => {
  return (
    <>
      <p>
        press hotkey ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> +{' '}
        <kbd>O</kbd>, then click the HTML element you wish to inspect.
      </p>
      <p>
        press hotkey ⌨️ <kbd>command ⌘</kbd> + 🖱 click, show component tree.
      </p>
      <Tree />
      <p>
        press hotkey ⌨️ <kbd>esc</kbd> or 🖱 right-click to exit inspect.
      </p>
    </>
  );
});

export default Notes;
