// playground/webpack-next/src/components/Notes.tsx
export default function Notes() {
  return (
    <div>
      <div>
        <h2>Enable inspector</h2>
        <p>
          shortcut key: ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> +
          <kbd>O</kbd>
        </p>
      </div>
      <div>
        <h2>Exit inspector</h2>
        <p>
          shortcut key 1: ⌨️ <kbd>Options ⌥</kbd> + <kbd>Command ⌘</kbd> +{' '}
          <kbd>O</kbd>, shortcut key 2: ⌨️ <kbd>esc</kbd> , shortcut key 3:
          🖱right click
        </p>
      </div>
    </div>
  );
}

// playground/vite-vue/src/components/Notes.vue
<template>
  <div>
    <h2>Enable inspector</h2>
    <p>
      shortcut key: ⌨️ <kbd>option ⌥</kbd> + <kbd>command ⌘</kbd> +
      <kbd>O</kbd>
    </p>
  </div>
  <div>
    <h2>Exit inspector</h2>
    <p>
      shortcut key 1: ⌨️ <kbd>Options ⌥</kbd> + <kbd>Command ⌘</kbd> +
      <kbd>O</kbd>, shortcut key 2: ⌨️ <kbd>esc</kbd> , shortcut key 3: 🖱right
      click
    </p>
  </div>
</template>
